controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    # mower_controller:
    #   type: effort_controllers/JointGroupEffortController

diff_drive_base_controller:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.32
    wheel_radius: 0.083
    wheels_per_side: 1

    use_stamped_vel: false

# mower_controller:
#   ros__parameters:
#     joints: ['mower_joint']
#     publish_rate: 50.0
