version: '2.3'
services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "12345:80"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20
  workspace:
    build: ./
    ipc: host
    pid: host
    security_opt:
    - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    ports:
      - "2222:2222"
      - "8765:8765" # Foxglove Studio websocket
      - "9002:9002" # Gazebo websocket
    volumes:
    - /opt/ros
    - ../:/home/ws
    - build:/home/ws/build # keep container pre-build
    - install:/home/ws/install # keep container pre-build
    - log:/home/ws/log # keep container pre-build
    environment:
    - DISPLAY=:0
    volumes_from:
    - xserver
    depends_on:
    - xserver
  groot:
    profiles:
      - with_groot
    build:
      context: ./
      dockerfile: groot.Dockerfile
    ipc: host
    pid: host
    security_opt:
    - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
    - ../:/home/ws
    environment:
    - DISPLAY=:0
    volumes_from:
    - xserver
    - workspace
    depends_on:
    - xserver
    - workspace
volumes:
  build:
  install:
  log: