chassis:
  # x, y, z offset in m of chassis from center of robot
  offset: [-0.1, 0.0, -0.05]

  # width, height, length of chassis in m
  width: 0.325
  height: 0.10
  length: 0.6

mower:
  # x, y, z offset in m of mower from center of robot
  offset: [0.15, 0.0, -0.001]

  # mower blades cut radius in m when spinning 
  cut_radius: 0.065

  # thickness in m
  thickness: 0.01
  # mass in kg
  mass: 0.05

wheel:
  # x, y, z offset in m of wheel from center of robot
  # for the left and right wheels, the y offset is positive and negative respectively
  offset: [0, 0.16, 0]
  # mass in kg
  mass: 0.2

  # radius in m
  radius: 0.0925
  # thickness in m
  thickness: 0.05

  # velocity in m/s
  velocity: 
    max: 0.2
    min: -0.2
  # gear ratio between motor and wheel
  gear_ratio: 1

caster_wheel:
  # x, y offset in m of caster wheel from center of chassis
  offset: [0.5, 0.1]
  radius: 0.0925
  mass: 0.05

gps:
  antenna:
    # x, y, z offset in m of gps antenna from center of chassis
    offset: [0.3, 0.0, 0.2]

battery:
  empty_voltage: 25.0
  full_voltage: 28.5